### ISSUE TITLE
The implementation of Codable for geometry types is not compatible with swift data

### ISSUE THREAD

**Issue by JesseCrocker** [Outdooractive/gis-tools#44]
The implementation of `Codable` for geometry types is not compatible with SwiftData. Saving a model with a LineString as a property produces the following error:

```
SwiftData/ModelCoders.swift:286: Fatal error: Composite Coder only supports Keyed Container
```

I have an [branch](https://github.com/JesseCrocker/gis-tools/commit/ff0bf6f11ab66f7b2feae0554aea043ce6eedfa4) that fixes this, but I think it changes how things are serialized, so it does not serve as a drop in replacement for the current version(or maybe it does, I'm not sure). I think it is possible to make a version that would be a drop in replacement(but maybe it isn't), at the expense or somewhat more repeated code.

Is this a change you would be interested in? If so I can work on preparing a PR. But i also understand if you are not, as this seems like a somewhat niche use.

**Comment by trasch** [comment]
@JesseCrocker  If you maybe could create a small demo project then I can have a look as well and see if I can find some time for this...
