### ISSUE TITLE
Parsing OSM tiles on WatchOS fails due to feature id overflow

### ISSUE THREAD

**Issue by JeffLutzenberger** [Outdooractive/gis-tools#45]
It looks like integer feature ids should be explicitly cast to `UInt64` on WatchOS. I have a branch with tests for this. 

Gist for discussion: https://gist.github.com/JeffLutzenberger/369d3062dafb5925d9641119eef41edd
 
(MVT tile spec: https://github.com/mapbox/vector-tile-spec/issues/94)

**Comment by trasch** [comment]
@JeffLutzenberger Thank you for bringing this up.

There are two conflicting definitions here:

[GeoJSON](https://www.rfc-editor.org/rfc/rfc7946#section-3.2):
   o  If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number.

Meaning, a GeoJSON id could be any Int, positive or negative.

[MVT Spec](https://github.com/Outdooractive/mvt-tools/blob/9ddfaa0c47b304bd3aa5cba7c201100738f97a3d/Sources/MVTTools/VectorTile_Tile.swift#L156):
    `var id: UInt64 {...}`

So an Unsigned Integer in vector tiles...

In the end, we need a solution that works with both:
- GeoJSON FeatureId needs to support Int and UInt64
- [MVT parsing](https://github.com/Outdooractive/mvt-tools/blob/9ddfaa0c47b304bd3aa5cba7c201100738f97a3d/Sources/MVTTools/VectorTileDecoder.swift#L150) needs a change

Do you have an example URL for a OSM tile with an overflowing id?

**Comment by trasch** [comment]
... and I have to admit that it was rather shortsighted of me to not handle this correctly right from the beginning... 🙄

**Comment by JeffLutzenberger** [comment]
I'll grab a tile for you today. I'm also wondering if Int64 would suffice.

**Comment by JeffLutzenberger** [comment]
Here's one that fails. Parse with Ultra 2 simulator or device:

[osm-8-41-101.pbf.zip](https://github.com/Outdooractive/gis-tools/files/14639083/osm-8-41-101.pbf.zip)

**Comment by trasch** [comment]
@JeffLutzenberger 

I think it should work now with https://github.com/Outdooractive/mvt-tools/pull/18 and https://github.com/Outdooractive/gis-tools/pull/46, but I will test it later

**Comment by trasch** [comment]
@JeffLutzenberger The new `uint64Value` property on `Feature.Identifier` should give you consistent access to a `UInt64` id for all OSM features, on all platforms. I hope this solves your problem... (?)

**Comment by JeffLutzenberger** [comment]
Testing now. Looks good so far!

**Comment by trasch** [comment]
@JeffLutzenberger How is it going? Everything good so far?

**Comment by JeffLutzenberger** [comment]
So far, so good! Thanks for the quick response and engagement on this.

**Comment by trasch** [comment]
I will merge this next week if everything is working now, so that this can be closed... :-)
